My capstone project
julzedz/Conference pull request #1
Opened 2022-09-16 21:27 UTC by julzedz

## AR Summit

In my capstone project, I created and [deployed](https://julzedz.github.io/Conference/) an online website for an Augmented Reality Art Summit in line with the Microverse capstone project requirements.

In [this loom video](https://loom.com/share/9a4aa3d2434c41fd9e68ba32600226f1), I present a demo of the project features.

2022-09-16 22:39 UTC, ichala requested changes
Hi @julzedz , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No linters errors✅ 
- Good Design ✅ 

🛑Note:  Your Presentation video looks good, but please note that you need to highlight a piece of the code that you find interesting or proud of.

 ## Required Changes ♻️

- [ ] _**check the comments below**_


## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 22:39 UTC, ichala commented on about.html
> +      </ul>
- [ ] the desktop version of the about page should have a link to the home page kindly add it as you did for the mobile menu

2022-09-16 22:39 UTC, ichala commented on about.html
> +        <li class="menu_item presentation">
- [ ] the desktop navbar looks awesome, kindly try to reduce the spaces between the links so they look correctly aligned to the right as shown in the template 

![image](https://user-images.githubusercontent.com/89282221/190811331-14157c9f-09cc-4f45-9c5a-4fb86cf8dc0b.png)

2022-09-16 22:39 UTC, ichala commented on about.html
> +        <img src="imgs/ar-art-summit-2022-600x315.jpeg" alt="summit logo">
- [ ] kindly reduce the size of the image that represent summit logo to match the template design


![image](https://user-images.githubusercontent.com/89282221/190816303-ddd4dd13-a803-47e6-89cf-9b6ea368e79e.png)

2022-09-16 22:39 UTC, ichala commented on about.html
> +  </footer>
- [ ] the about page footer looks awesome and perfect, kindly apply the same alignment for the index footer as well

> TIP: in general the content of the footer should be the same on all pages , so you can put the same layout and text of the about page in the footer of index page and the colors can stay the same white for index & dark for about 💯 

About Footer :
![image](https://user-images.githubusercontent.com/89282221/190821656-ca14411e-5992-4b3a-b83f-267ec5dfb944.png)

index footer : 
![image](https://user-images.githubusercontent.com/89282221/190822356-6ef6089d-d5c2-41f3-9f5a-d053eba0e87f.png)

2022-09-16 22:39 UTC, ichala commented on about.html
> +    <a href=""><img src="imgs/twitter.png" alt=""></a>
- [ ] all of your pages should be accessible, currently, you have some empty  `alt` attributes kindly add meaningful alts for each `img` tag you have

2022-09-16 22:39 UTC, ichala commented on about.html
> +        </div>
- [ ]  all of your pages should be accessible, currently, you have some empty alt attributes kindly add meaningful alts for each img tag you have

2022-09-16 22:39 UTC, ichala commented on about.html
> +      <img src="imgs/logo_cc_w_147x35.png" id="desktop-footer" alt="">
- [ ]  all of your pages should be accessible, currently, you have some empty alt attributes kindly add meaningful alts for each img tag you have

2022-09-16 22:39 UTC, ichala commented on index.html
> +    <a href=""><img class="icon" src="imgs/twitter.png" alt=""></a>
- [ ]  all of your pages should be accessible, currently, you have some empty alt attributes kindly add meaningful alts for each img tag you have

2022-09-17 00:59 UTC, emmiiorji approved these changes
Hi @julzedz, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://user-images.githubusercontent.com/20554583/190834315-b4a3a4fb-7444-4c4f-af77-fce03d73c168.gif)

## Good Highlights✔

- Requested changes have been implemented
- Good commit messages
- Adherence to GitHub flow
- Linter checks are passing

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 11:05 UTC, merged